spring.application.name:
  spoilme
server:
  port: 8080
spring.datasource:
  driver-class-name:
    com.mysql.cj.jdbc.Driver
  url:
      jdbc:mysql://kin.qinsy.ltd:3306/spoilme?useUnicode=true&characterEncoding=UTF-8
  username:
    spoilme
  password:
    spoilme

spring:
  data:
    redis:
      host: kin.qinsy.ltd
      password: 123456
      port: 6379
netty:
  socket:
    port: 8081