spring.application.name:
  spoilme
spring.datasource:
  driver-class-name:
    com.mysql.cj.jdbc.Driver
  url:
    jdbc:mysql://127.0.0.1:3306/spoilme?useUnicode=true&characterEncoding=UTF-8
  username:
    spoilme
  password:
    spoilme
spring:
  data:
    redis:
      host: 127.0.0.1
      password: lxz2100301322@
      port: 6379

# mybatis日志输出路径 : Console; 驼峰命名自动映射开关: 打开
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 修改端口号
server:
  port: 8080

# 开始事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransctionManager: debug

#netty服务端口
netty:
  socket:
    port: 8081
#minio
minio:
  bucket: spoilme
  endpoint: http://127.0.0.1:9000
  accesskey: vlxz
  secretKey: 90156115vlxz@